# Generated by Django 3.0.8 on 2020-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_type', models.CharField(choices=[('Reminder', 'Reminder'), ('Cheerleading', 'Cheerleading'), ('BCI', 'Bci'), ('Informational', 'Info'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=25, verbose_name='Text Type')),
                ('body', models.TextField(unique=True, verbose_name='Text Body')),
                ('n_chars', models.PositiveIntegerField(blank=True, null=True, verbose_name='Text Length')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
            ],
            options={
                'verbose_name': 'Text Details',
                'verbose_name_plural': 'Text Details',
            },
        ),
    ]
