# Generated by Django 3.0.8 on 2020-08-13 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSchedule',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Goal Description')),
                ('goal_description', models.TextField(blank=True, null=True, verbose_name='Goal Description')),
                ('start', models.DateField(verbose_name='Goal Schedule Start Date')),
                ('end', models.DateField(blank=True, verbose_name='Goal Schedule End Date')),
            ],
            options={
                'verbose_name': 'User Goal Schedule',
                'verbose_name_plural': 'User Goal Schedules',
            },
        ),
        migrations.CreateModel(
            name='GoalSchedulesBookings_BRIDGE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextBooking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_send_period', models.DateTimeField()),
                ('end_send_period', models.DateTimeField()),
                ('final_send_dt', models.DateTimeField(blank=True)),
                ('goal_schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.GoalSchedule')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.TextDetails')),
            ],
            options={
                'verbose_name': 'Text Booking',
                'verbose_name_plural': 'Text Bookings',
            },
        ),
    ]
