# Generated by Django 3.0.8 on 2020-08-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalschedulesbookings_bridge',
            name='goal_schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.GoalSchedule'),
        ),
        migrations.AddField(
            model_name='goalschedulesbookings_bridge',
            name='text_booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.TextBooking'),
        ),
        migrations.AddField(
            model_name='goalschedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
