# Generated by Django 3.0.8 on 2020-08-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('n_texts', models.PositiveIntegerField()),
                ('runtime_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTexts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('delta_days', models.PositiveIntegerField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.TextDetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramParticipantRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('abandoned', models.BooleanField(default=django.db.models.deletion.SET_NULL, null=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
